export const INITIAL_LOAD = 'INITIAL_LOAD'
export const FETCH_NIFTY_INDEX = 'FETCH_NIFTY_INDEX'
export const ADD_NIFTY_INDEX = 'ADD_NIFTY_INDEX'
export const ADD_ALL_NIFTY_STOCKS = 'ADD_ALL_NIFTY_STOCKS'
export const ADD_BANK_NIFTY_INDEX = 'ADD_BANK_NIFTY_INDEX'
export const ADD_ERROR = 'ADD_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const SET_LOADING = 'SET_LOADING'
export const ADD_CURRENT_SELECTED_DATE = 'ADD_CURRENT_SELECTED_DATE'
export const ADD_CURRENT_SELECTED_INDEX = 'ADD_CURRENT_SELECTED_INDEX'
export const SET_SELECTED_MARKET = 'SET_SELECTED_MARKET'
export const ADD_NASDAQ_INDEX = 'ADD_NASDAQ_INDEX'
export const ADD_SP500_INDEX = 'ADD_SP500_INDEX'
export const ADD_ALL_US_STOCKS = 'ADD_ALL_US_STOCKS'
export const INITIAL_LOAD_US = 'INITIAL_LOAD_US'
export const ALL_NIFTY_STOCKS = [
  "ADANIPORTS.NS",
  "ASIANPAINT.NS",
  "AXISBANK.NS",
  "BAJAJ-AUTO.NS",
  "BAJFINANCE.NS",
  "BAJAJFINSV.NS",
  "BPCL.NS",
  "BHARTIARTL.NS",
  "BRITANNIA.NS",
  "CIPLA.NS",
  "COALINDIA.NS",
  "DRREDDY.NS",
  "EICHERMOT.NS",
  "GAIL.NS",
  "GRASIM.NS",
  "HINDUNILVR.NS",
  "HINDALCO.NS",
  "HEROMOTOCO.NS",
  "HDFC.NS",
  "HDFCBANK.NS",
  "HCLTECH.NS",
  "INFRATEL.NS",
  "INFY.NS",
  "INDUSINDBK.NS",
  "IOC.NS",
  "ITC.NS",
  "ICICIBANK.NS",
  "JSWSTEEL.NS",
  "KOTAKBANK.NS",
  "LT.NS",
  "M\u0026M.NS",
  "MARUTI.NS",
  "NTPC.NS",
  "NESTLEIND.NS",
  "ONGC.NS",
  "POWERGRID.NS",
  "RELIANCE.NS",
  "SHREECEM.NS",
  "SBIN.NS",
  "SUNPHARMA.NS",
  "TCS.NS",
  "TATAMOTORS.NS",
  "TATASTEEL.NS",
  "TECHM.NS",
  "TITAN.NS",
  "UPL.NS",
  "ULTRACEMCO.NS",
  "VEDL.NS",
  "WIPRO.NS",
  "RELIANCE.NS",
  "TCS.NS",
  "HDFCBANK.NS",
  "INFY.NS",
  "ICICIBANK.NS"
]

export const ALL_US_STOCKS = [
  "AAPL"   // Apple - Testing with just one stock
]